#!/bin/bash

RECOLLECT=/var/www/recollect
export PERL5LIB="$RECOLLECT/lib"

exec 2>&1 \
    /usr/local/bin/starman --listen 127.0.0.1:2080 --workers 4 --preload-app \
        --user recollect --group www-data \
        $RECOLLECT/production.psgi >> /var/log/recollect-server.log 2>&1
